import type {
  ServiceCategoryItem,
  ServiceCategorySlug,
  ServiceHubCategory,
} from "@/shared/types/api";

export const serviceCategorySlugValues: ServiceCategorySlug[] = [
  "services",
  "history-and-culture",
  "nature",
  "museums-and-exhibitions",
  "restaurants",
  "sightseeing",
  "hotels",
  "taxi",
  "hospitals",
  "pharmacies",
  "atms",
];

export const fallbackServiceHubCategories: ServiceHubCategory[] = [
  {
    id: "services",
    slug: "services",
    path: "/service/services",
    name: "Services",
    subtitle: "Travel support and local essentials",
    description: "Local support, practical operators, and trustworthy tourism services for a smoother trip.",
    group: "core",
    icon: "briefcase",
    image: "https://images.unsplash.com/photo-1521295121783-8a321d551ad2?auto=format&fit=crop&w=1200&q=80",
    accent: "#D97706",
    sourceEndpoint: "/api/services",
    tags: ["Support", "Guidance"],
    order: 1,
    isActive: true,
  },
  {
    id: "history-and-culture",
    slug: "history-and-culture",
    path: "/service/history-and-culture",
    name: "History & Culture",
    subtitle: "Stories, heritage, and identity",
    description: "Discover landmarks, cultural anchors, and must-know heritage places across Karakalpakstan.",
    group: "core",
    icon: "landmark",
    image: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1200&q=80",
    accent: "#9A3412",
    sourceEndpoint: "/api/places",
    tags: ["Heritage", "Culture"],
    order: 2,
    isActive: true,
  },
  {
    id: "nature",
    slug: "nature",
    path: "/service/nature",
    name: "Nature",
    subtitle: "Wide landscapes and open air",
    description: "Natural escapes, scenic viewpoints, and outdoor experiences that work beautifully on a phone demo.",
    group: "core",
    icon: "mountain",
    image: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    accent: "#0F766E",
    sourceEndpoint: "/api/places",
    tags: ["Landscape", "Outdoor"],
    order: 3,
    isActive: true,
  },
  {
    id: "museums-and-exhibitions",
    slug: "museums-and-exhibitions",
    path: "/service/museums-and-exhibitions",
    name: "Museums & Exhibitions",
    subtitle: "Art, archives, and collections",
    description: "Browse museum-led experiences and exhibition moments with strong educational value.",
    group: "core",
    icon: "museum",
    image: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80",
    accent: "#6D28D9",
    sourceEndpoint: "/api/places",
    tags: ["Museum", "Exhibition"],
    order: 4,
    isActive: true,
  },
  {
    id: "restaurants",
    slug: "restaurants",
    path: "/service/restaurants",
    name: "Restaurants",
    subtitle: "Dining worth adding to the plan",
    description: "Food stops, local dining, and restaurant picks that fit naturally into route planning.",
    group: "core",
    icon: "utensils",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    accent: "#C2410C",
    sourceEndpoint: "/api/services",
    tags: ["Dining", "Food"],
    order: 5,
    isActive: true,
  },
  {
    id: "sightseeing",
    slug: "sightseeing",
    path: "/service/sightseeing",
    name: "Sightseeing",
    subtitle: "Fast picks for a strong first impression",
    description: "Best visual moments and high-impact stops for short visits, demos, and curated day plans.",
    group: "core",
    icon: "camera",
    image: "https://images.unsplash.com/photo-1501555088652-021faa106b9b?auto=format&fit=crop&w=1200&q=80",
    accent: "#0EA5E9",
    sourceEndpoint: "/api/places",
    tags: ["Highlights", "Photo spots"],
    order: 6,
    isActive: true,
  },
  {
    id: "hotels",
    slug: "hotels",
    path: "/service/hotels",
    name: "Hotels",
    subtitle: "Stay planning made simple",
    description: "Accommodation choices for MVP demos, convenient bookings, and easy trip packaging.",
    group: "core",
    icon: "bed",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    accent: "#1D4ED8",
    sourceEndpoint: "/api/services",
    tags: ["Stay", "Booking"],
    order: 7,
    isActive: true,
  },
  {
    id: "taxi",
    slug: "taxi",
    path: "/service/taxi",
    name: "Taxi numbers",
    subtitle: "Quick local transport help",
    description: "Fast-call transport contacts for arrivals, station pickups, and moving between stops.",
    group: "utility",
    icon: "car",
    image: "https://images.unsplash.com/photo-1511527844068-006b95d162c2?auto=format&fit=crop&w=1200&q=80",
    accent: "#F59E0B",
    sourceEndpoint: "/api/utility/taxi",
    tags: ["Transport", "Phone"],
    order: 8,
    isActive: true,
  },
  {
    id: "hospitals",
    slug: "hospitals",
    path: "/service/hospitals",
    name: "Hospitals",
    subtitle: "Emergency and medical support",
    description: "Reliable healthcare references for travelers when practical help matters most.",
    group: "utility",
    icon: "activity",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80",
    accent: "#DC2626",
    sourceEndpoint: "/api/utility/hospitals",
    tags: ["Emergency", "Healthcare"],
    order: 9,
    isActive: true,
  },
  {
    id: "pharmacies",
    slug: "pharmacies",
    path: "/service/pharmacies",
    name: "Pharmacies",
    subtitle: "Medicine and essentials nearby",
    description: "Pharmacy references that keep the experience practical and travel-ready.",
    group: "utility",
    icon: "pill",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
    accent: "#059669",
    sourceEndpoint: "/api/utility/pharmacies",
    tags: ["Medicine", "Essentials"],
    order: 10,
    isActive: true,
  },
  {
    id: "atms",
    slug: "atms",
    path: "/service/atms",
    name: "ATMs",
    subtitle: "Cash access when you need it",
    description: "Cash-out points and practical finance helpers for local movement and bookings.",
    group: "utility",
    icon: "credit-card",
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=1200&q=80",
    accent: "#0F766E",
    sourceEndpoint: "/api/utility/atms",
    tags: ["Cash", "Finance"],
    order: 11,
    isActive: true,
  },
];

export const fallbackServiceItems: Record<ServiceCategorySlug, ServiceCategoryItem[]> = {
  services: [
    {
      id: "service-local-concierge",
      categorySlug: "services",
      kind: "service",
      name: "Baramiz Local Concierge",
      shortDescription: "Fast support for airport pickup, guide coordination, and local logistics.",
      fullDescription: "A practical support line for arranging transport, quick trip advice, and travel continuity during the MVP demo.",
      city: "Nukus",
      region: "Karakalpakstan",
      address: "Central tourism district",
      image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Support", "Concierge", "Fast help"],
      badge: "Recommended",
      meta: "Ideal for first-time visitors",
      workingHours: "08:00 - 22:00",
      phone: "+998 97 700 10 10",
      telegram: "https://t.me/baramiz_support",
      website: "https://baramiz.app",
      source: "fallback",
      serviceType: "concierge",
    },
    {
      id: "service-cultural-assist",
      categorySlug: "services",
      kind: "service",
      name: "Cultural Host Desk",
      shortDescription: "On-ground assistance for museum visits, local etiquette, and route support.",
      city: "Nukus",
      region: "Karakalpakstan",
      address: "Savitsky Museum area",
      image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Guide", "Culture", "Planning"],
      meta: "Short-notice support available",
      workingHours: "09:00 - 19:00",
      phone: "+998 97 710 20 20",
      source: "fallback",
      serviceType: "local-support",
    },
  ],
  "history-and-culture": [
    {
      id: "history-state-museum",
      categorySlug: "history-and-culture",
      kind: "service",
      name: "Karakalpak Cultural Heritage Center",
      shortDescription: "A strong cultural stop for local history, identity, and traditional crafts.",
      city: "Nukus",
      region: "Karakalpakstan",
      image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Heritage", "Craft", "Culture"],
      meta: "Best for first-time discovery",
      source: "fallback",
      serviceType: "heritage-place",
    },
  ],
  nature: [
    {
      id: "nature-desert-view",
      categorySlug: "nature",
      kind: "service",
      name: "Ustyurt Scenic Stop",
      shortDescription: "Wide-open desert landscapes and a memorable outdoor photo moment.",
      city: "Moynaq",
      region: "Karakalpakstan",
      image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Nature", "Landscape", "Outdoor"],
      meta: "Sunrise and sunset friendly",
      source: "fallback",
      serviceType: "nature-stop",
    },
  ],
  "museums-and-exhibitions": [
    {
      id: "museum-archive",
      categorySlug: "museums-and-exhibitions",
      kind: "service",
      name: "Regional Exhibition Hall",
      shortDescription: "A flexible museum-style visit with collections and temporary exhibition moments.",
      city: "Nukus",
      region: "Karakalpakstan",
      image: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Museum", "Exhibition"],
      meta: "Easy to add to a half-day route",
      source: "fallback",
      serviceType: "museum-stop",
    },
  ],
  restaurants: [
    {
      id: "restaurant-plov-house",
      categorySlug: "restaurants",
      kind: "restaurant",
      name: "Nukus Plov House",
      shortDescription: "Comfortable local dining with reliable service for groups and judges.",
      city: "Nukus",
      region: "Karakalpakstan",
      address: "City center",
      image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Local cuisine", "Dinner", "Group friendly"],
      priceLabel: "$$",
      rating: 4.7,
      workingHours: "11:00 - 23:00",
      phone: "+998 97 720 12 12",
      source: "fallback",
      cuisine: "Karakalpak & Uzbek",
    },
  ],
  sightseeing: [
    {
      id: "sightseeing-river-walk",
      categorySlug: "sightseeing",
      kind: "service",
      name: "Nukus City View Route",
      shortDescription: "A quick sightseeing sequence built for a strong demo-friendly impression.",
      city: "Nukus",
      region: "Karakalpakstan",
      image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Highlights", "Photo spots"],
      meta: "Works well in short itineraries",
      source: "fallback",
      serviceType: "highlight-route",
    },
  ],
  hotels: [
    {
      id: "hotel-premier-nukus",
      categorySlug: "hotels",
      kind: "hotel",
      name: "Premier Stay Nukus",
      shortDescription: "A polished city-base option with easy transport access and clean amenities.",
      city: "Nukus",
      region: "Karakalpakstan",
      address: "Central business district",
      image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Stay", "Comfort", "Central"],
      priceLabel: "$85 / night",
      rating: 4.6,
      workingHours: "24/7",
      phone: "+998 97 730 30 30",
      website: "https://baramiz.app",
      source: "fallback",
      amenities: ["Wi-Fi", "Breakfast", "Airport transfer"],
    },
  ],
  taxi: [
    {
      id: "taxi-nukus-dispatch",
      categorySlug: "taxi",
      kind: "contact",
      name: "Nukus Taxi Dispatch",
      shortDescription: "Reliable city rides for airport transfers and same-day travel between stops.",
      city: "Nukus",
      region: "Karakalpakstan",
      image: "https://images.unsplash.com/photo-1511527844068-006b95d162c2?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Taxi", "Transfer"],
      contactLabel: "24/7 dispatch",
      phone: "+998 97 711 00 00",
      workingHours: "24/7",
      source: "fallback",
      utilityType: "taxi",
    },
    {
      id: "taxi-regional-travel",
      categorySlug: "taxi",
      kind: "contact",
      name: "Regional Driver Network",
      shortDescription: "Longer-distance taxi support for Moynaq, museums, and nature stops.",
      city: "Nukus",
      region: "Karakalpakstan",
      image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Intercity", "Private ride"],
      contactLabel: "Booked rides",
      phone: "+998 97 722 22 22",
      workingHours: "07:00 - 23:00",
      source: "fallback",
      utilityType: "taxi",
    },
  ],
  hospitals: [
    {
      id: "hospital-nukus-central",
      categorySlug: "hospitals",
      kind: "utility",
      name: "Nukus Central Hospital",
      shortDescription: "Primary medical support point with emergency access and city-center reach.",
      city: "Nukus",
      region: "Karakalpakstan",
      address: "A. Dosnazarov street",
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Emergency", "Medical"],
      badge: "Emergency ready",
      workingHours: "24/7",
      phone: "+998 61 222 11 11",
      source: "fallback",
      utilityType: "hospital",
    },
  ],
  pharmacies: [
    {
      id: "pharmacy-city-care",
      categorySlug: "pharmacies",
      kind: "utility",
      name: "City Care Pharmacy",
      shortDescription: "Travel basics, medicine access, and central location for quick stops.",
      city: "Nukus",
      region: "Karakalpakstan",
      address: "Main avenue",
      image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["Pharmacy", "Essentials"],
      workingHours: "08:00 - 23:00",
      phone: "+998 61 223 33 44",
      source: "fallback",
      utilityType: "pharmacy",
    },
  ],
  atms: [
    {
      id: "atm-center-bank",
      categorySlug: "atms",
      kind: "utility",
      name: "Central Bank ATM Zone",
      shortDescription: "A practical cash access point near hotels, food, and high-traffic city areas.",
      city: "Nukus",
      region: "Karakalpakstan",
      address: "Downtown Nukus",
      image: "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1200&q=80",
      gallery: [],
      tags: ["ATM", "Cash"],
      workingHours: "24/7",
      source: "fallback",
      utilityType: "atm",
    },
  ],
};

export const placeCategoryGroups: Partial<Record<ServiceCategorySlug, ("history" | "culture" | "museum" | "nature" | "adventure" | "food")[]>> = {
  "history-and-culture": ["history", "culture"],
  nature: ["nature", "adventure"],
  "museums-and-exhibitions": ["museum"],
};
